project:
  title: "Visa Rejection Rate"
  type: website
  output-dir: docs
  render:
    - index.qmd
  preview:
    port: 4200

format:
  html:
    echo: false
    theme: default
    page-layout: custom 
    margin-left: 20px
    margin-top: 10px 
    margin-right: 30px
    margin-bottom: 10px
    fontsize: 16px




