project:
  title: "Visa Rejection Rate"
  type: website
  output-dir: docs
  render:
    - index.qmd
  preview:
    port: 4200

format:
  html:
    toc: true
    toc-location: left
    number-sections: true
    echo: false
    theme: style/style.scss
    grid:
      sidebar-width: 200px
      body-width: 900px
      margin-width: 200px
      gutter-width: 0rem
    # page-layout: custom 
    margin-left: 20px
    margin-top: 10px 
    margin-right: 30px
    margin-bottom: 10px
    fontsize: 16px





